# Header
menu:
  首页: /
  剧集: /categories/tv-series
  电影: /categories/movie
  纪录片: /categories/documentary
  归档: /archives

# Default post title
default_post_title: Untitled

# Default post cover index page
default_cover_index: "http://placehold.it/450x450"

# Default post cover index page
default_cover_detail: "http://placehold.it/1300x500"

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light
  # LiveRe comments
  livere: MTAyMC8zMjQ0NC85MDA1

# Google Analytics Tracking ID
google_analytics: UA-102285693-1

# Social Accounts
twitter_url:
facebook_url:
behance_url:
googleplus_url:
dribble_url:
rss_url:
weibo_url: http://weibo.com/fengguzimuzu
weibo_title: 风骨字幕组的微博
qq_group_idkey: 30f8ed3b05c574368a573411bf03eae6ba121a085e0af01f0d05b9f67971c8af
qq_group_title: 加入风骨粉丝群 203998406
email_address: bonesbar@sina.com
email_title: 给我们发邮件

favicon: /img/favicon.ico